// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqVxaa5g3QkyLBnqubMGea1qcR_kG4IPE',
    appId: '1:343759281113:web:3139d230565df3d29597c8',
    messagingSenderId: '343759281113',
    projectId: 'flutter-chat-app-7bcf3',
    authDomain: 'flutter-chat-app-7bcf3.firebaseapp.com',
    storageBucket: 'flutter-chat-app-7bcf3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSyw8KmRyxN7J3MeFDYBfVRbUdXSdiyqQ',
    appId: '1:343759281113:android:49eb3e73d04e0e339597c8',
    messagingSenderId: '343759281113',
    projectId: 'flutter-chat-app-7bcf3',
    storageBucket: 'flutter-chat-app-7bcf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuMGCgOKG3Afu1zorx2vqkoqqOiIATd3U',
    appId: '1:343759281113:ios:84e505a8a02c050f9597c8',
    messagingSenderId: '343759281113',
    projectId: 'flutter-chat-app-7bcf3',
    storageBucket: 'flutter-chat-app-7bcf3.appspot.com',
    iosBundleId: 'com.example.chatAppp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuMGCgOKG3Afu1zorx2vqkoqqOiIATd3U',
    appId: '1:343759281113:ios:941550066a87908a9597c8',
    messagingSenderId: '343759281113',
    projectId: 'flutter-chat-app-7bcf3',
    storageBucket: 'flutter-chat-app-7bcf3.appspot.com',
    iosBundleId: 'com.example.chatAppp.RunnerTests',
  );
}
